[package]
name = "loom_deadlock"
version = "0.1.0"
authors = ["Mark Blum <mark.n.blum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loom = "0.4.1"
